spring:
  application:
    name: app
  datasource:
    username: ${db-user:product}
    password: ${db-password:product}
    url: jdbc:postgresql://${db.host:localhost}:${db.port:5432}/${db.name:app}?currentSchema=${db.schema:app}
