openapi: 3.1.0
info:
  title: Product API
  description: Product API
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: Local server
paths:
    /products:
        get:
          summary: List of products
          operationId: listProducts
          tags:
            - Product
          responses:
              '200':
                description: OK
                content:
                  application/json:
                    schema:
                      $ref: '#/components/schemas/ProductList'
    /products/{id}:
        get:
          summary: Get a product by id
          operationId: getProduct
          tags:
            - Product
          parameters:
            - name: id
              in: path
              required: true
              schema:
                type: string
                format: uuid
          responses:
              '200':
                description: OK
                content:
                  application/json:
                    schema:
                      $ref: '#/components/schemas/ProductV1'
              '404':
                description: Not found

components:
  schemas:
    ProductList:
        type: array
        items:
            $ref: '#/components/schemas/ProductV1'
    ProductV1:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        description:
           type: string
        priceInCents:
          type: integer
          format: int64
        createdAt:
          type: string
#          format: data-time
        updatedAt:
          type: string
#          format: date-time
